### ISSUE TITLE
cant use v2ray

### ISSUE THREAD

**Issue by mlopez119** [korn-sudo/Project-Fog#2]
I cant use v2ray.. I will attached the picture
![Screenshot 2021-08-12 142934](https://user-images.githubusercontent.com/82475090/129148901-8f68681e-8f38-4a9c-9ce2-13cf3748e391.png)
![Screenshot 2021-08-12 143033](https://user-images.githubusercontent.com/82475090/129148908-02756f00-8987-4a5b-8c81-64ae2e506907.png)

**Comment by studikumbang** [comment]
cant use v2ray too

**Comment by shukryshuk** [comment]
hi, still cant use v2ray isaw he updated the script.

**Comment by imranexltd** [comment]
same here v2ray panel not working

**Comment by malikshi** [comment]
I can easily fix this one.

**Comment by korn-sudo** [comment]
This is an issue has been resolved in version 2.5.3
