### ISSUE TITLE
bunch of errors.

### ISSUE THREAD

**Issue by malikshi** [korn-sudo/Project-Fog#3]
>/tmp/21196: line 259: /etc/stunnel/stunnel.conf: No such file or directory
sed: can't read /etc/stunnel/stunnel.conf: No such file or directory
sed: can't read /etc/stunnel/stunnel.conf: No such file or directory
sed: can't read /etc/stunnel/stunnel.conf: No such file or directory
sed: can't read /etc/stunnel/stunnel.conf: No such file or directory
sed: can't read /etc/stunnel/stunnel.conf: No such file or directory
sed: can't read /etc/stunnel/stunnel.conf: No such file or directory

another one
>/tmp/21196: line 937: /etc/privoxy/config: No such file or directory
sed: can't read /etc/privoxy/config: No such file or directory
sed: can't read /etc/privoxy/config: No such file or directory
sed: can't read /etc/privoxy/config: No such file or directory
Restarting Privoxy Proxy server...
Failed to restart privoxy.service: Unit privoxy.service not found.
/tmp/21196: line 978: /etc/squid/squid.conf: No such file or directory
sed: can't read /etc/squid/squid.conf: No such file or directory
sed: can't read /etc/squid/squid.conf: No such file or directory
sed: can't read /etc/squid/squid.conf: No such file or directory
sed: can't read /etc/squid/squid.conf: No such file or directory

another one
>sed: can't read /usr/local/lib/python2.7/dist-packages/shadowsocks/crypto/openssl.py: No such file or directory
sed: can't read /usr/local/lib/python3.4/dist-packages/shadowsocks/crypto/openssl.py: No such file or directory
sed: can't read /usr/local/lib/python3.5/dist-packages/shadowsocks/crypto/openssl.py: No such file or directory
sed: can't read /usr/local/lib/python3.6/dist-packages/shadowsocks/crypto/openssl.py: No such file or directory
sed: can't read /usr/local/lib/python3.7/dist-packages/shadowsocks/crypto/openssl.py: No such file or directory
sed: can't read /usr/local/lib/python3.8/dist-packages/shadowsocks/crypto/openssl.py: No such file or directory
sed: can't read /usr/local/lib/python3.9/dist-packages/shadowsocks/crypto/openssl.py: No such file or directory

another one
>sed: can't read /etc/nginx/conf.d/vps.conf: No such file or directory
sed: can't read /etc/nginx/conf.d/vps.conf: No such file or directory
sed: can't read /etc/nginx/conf.d/monitoring.conf: No such file or directory

another one
>/tmp/21196: line 1218: virtualenv: command not found
/tmp/21196: line 1219: bin/activate: No such file or directory
/tmp/21196: line 1220: pip: command not found

another one
>Failed to restart nginx.service: Unit nginx.service not found.
 Configuring Startup Application Automation...
Created symlink /etc/systemd/system/multi-user.target.wants/projectfogstartup.service → /etc/systemd/system/projectfogstartup.service.
Job for projectfogstartup.service failed because the control process exited with error code.
See "systemctl status projectfogstartup.service" and "journalctl -xe" for details.

too much errors and it's closed script I can't help it without knowing what's inside

**Comment by korn-sudo** [comment]
rebuild your vps and open all ports.

**Comment by Rendevior** [comment]
> > /tmp/21196: line 259: /etc/stunnel/stunnel.conf: No such file or directory
> > sed: can't read /etc/stunnel/stunnel.conf: No such file or directory
> > sed: can't read /etc/stunnel/stunnel.conf: No such file or directory
> > sed: can't read /etc/stunnel/stunnel.conf: No such file or directory
> > sed: can't read /etc/stunnel/stunnel.conf: No such file or directory
> > sed: can't read /etc/stunnel/stunnel.conf: No such file or directory
> > sed: can't read /etc/stunnel/stunnel.conf: No such file or directory
> 
> another one
> 
> > /tmp/21196: line 937: /etc/privoxy/config: No such file or directory
> > sed: can't read /etc/privoxy/config: No such file or directory
> > sed: can't read /etc/privoxy/config: No such file or directory
> > sed: can't read /etc/privoxy/config: No such file or directory
> > Restarting Privoxy Proxy server...
> > Failed to restart privoxy.service: Unit privoxy.service not found.
> > /tmp/21196: line 978: /etc/squid/squid.conf: No such file or directory
> > sed: can't read /etc/squid/squid.conf: No such file or directory
> > sed: can't read /etc/squid/squid.conf: No such file or directory
> > sed: can't read /etc/squid/squid.conf: No such file or directory
> > sed: can't read /etc/squid/squid.conf: No such file or directory
> 
> another one
> 
> > sed: can't read /usr/local/lib/python2.7/dist-packages/shadowsocks/crypto/openssl.py: No such file or directory
> > sed: can't read /usr/local/lib/python3.4/dist-packages/shadowsocks/crypto/openssl.py: No such file or directory
> > sed: can't read /usr/local/lib/python3.5/dist-packages/shadowsocks/crypto/openssl.py: No such file or directory
> > sed: can't read /usr/local/lib/python3.6/dist-packages/shadowsocks/crypto/openssl.py: No such file or directory
> > sed: can't read /usr/local/lib/python3.7/dist-packages/shadowsocks/crypto/openssl.py: No such file or directory
> > sed: can't read /usr/local/lib/python3.8/dist-packages/shadowsocks/crypto/openssl.py: No such file or directory
> > sed: can't read /usr/local/lib/python3.9/dist-packages/shadowsocks/crypto/openssl.py: No such file or directory
> 
> another one
> 
> > sed: can't read /etc/nginx/conf.d/vps.conf: No such file or directory
> > sed: can't read /etc/nginx/conf.d/vps.conf: No such file or directory
> > sed: can't read /etc/nginx/conf.d/monitoring.conf: No such file or directory
> 
> another one
> 
> > /tmp/21196: line 1218: virtualenv: command not found
> > /tmp/21196: line 1219: bin/activate: No such file or directory
> > /tmp/21196: line 1220: pip: command not found
> 
> another one
> 
> > Failed to restart nginx.service: Unit nginx.service not found.
> > Configuring Startup Application Automation...
> > Created symlink /etc/systemd/system/multi-user.target.wants/projectfogstartup.service → /etc/systemd/system/projectfogstartup.service.
> > Job for projectfogstartup.service failed because the control process exited with error code.
> > See "systemctl status projectfogstartup.service" and "journalctl -xe" for details.
> 
> too much errors and it's closed script I can't help it without knowing what's inside

You prolly run the script in non root user

**Comment by malikshi** [comment]
> You prolly run the script in non root user
I'm running root user
