### ISSUE TITLE
Apache2 not running after installation 

### ISSUE THREAD

**Issue by zeeid** [korn-sudo/Project-Fog#7]
hello good morning
ihave a problem after installing this script

my apache2 not start
and i try to start with comman
got this error : 
_Job for apache2.service failed because the control process exited with error code. See "systemctl status apache2.service" and "journalctl -xe" for details._

and i cant open myippublic:54321 web panel and else

Help me please
Thank you

**Comment by korn-sudo** [comment]
There is no correlation between v2ray and apache2. Rebuild your server and install this script on a fresh vps.

Due to apache2 occupying port 80, I removed it; however, this has no effect on v2ray.

**Comment by zeeid** [comment]
Okay, Thank you so much
