### ISSUE TITLE
openvpn connect udp but no internet

### ISSUE THREAD

**Issue by yadude87** [korn-sudo/Project-Fog#8]
i get this in openvpn UDP send exception: send: No route to host
openvpn tcp doesnt connect at all
also i cant access fog website i change line 45 to create account on site says connection failed’ 
i changed but still same
do i need to open a port other then 85

VIP Server","123.123.123.123","12345678"

fogserverip i put my vps ip
server-root i put my root password
i just did a sample picture not my info 
but username i put my vps ip
password i put what i wrote on line 45 like shown above
i get this message

Connection Failed...
<img width="1128" alt="Screen Shot 2022-02-24 at 10 25 14 PM" src="https://user-images.githubusercontent.com/95441223/155593268-47d7ab44-410c-4600-b62c-c65edb94ec09.png">

**Comment by korn-sudo** [comment]
OCS Panel role is creating an account.  Just put password and no need to put ip address. It is impossible to see "fogserverip" after installation because it is automatically replaced your IP Address.

OpenVPN has no connection or no effect in OCS Panel. 



Rebuild your VPS then install Project fog.

**Comment by korn-sudo** [comment]
I already provided all information and guide in readme.md

**Comment by korn-sudo** [comment]
For the picture you shown.

OCS Panel It is for creating "New Account"  and not for logging your account. It is already stated in readme.md

**Comment by korn-sudo** [comment]
I suggest read again readme.md especially this:
![image](https://user-images.githubusercontent.com/76937659/155688221-fbec7f5b-d1ff-41c8-9659-bd4c0f69f0d9.png)
